/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package se.hyperlab.mixpanel;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

import android.content.Context;
import android.app.Activity;

import org.json.JSONObject;
import java.util.HashMap;

import com.mixpanel.android.mpmetrics.MixpanelAPI;

@Kroll.module(name="Timixpanel", id="se.hyperlab.mixpanel")
public class TimixpanelModule extends KrollModule
{

	// Standard Debugging variables
	private static final String TAG = "TimixpanelModule";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	private MixpanelAPI mixpanel;

	public TimixpanelModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(TAG, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	@Override
	public void onDestroy(Activity activity)
	{
		// This method is called when the root context is being destroyed
		mixpanel.flush();

		super.onDestroy(activity);
	}

	// Methods
	@Kroll.method
	public void initWithToken(@Kroll.argument String token)
	{
		Log.d(TAG, "Mixpanel initWithToken: " + token);
		mixpanel = MixpanelAPI.getInstance(TiApplication.getInstance(), token);

		// identify must be called before interacting with People API
		mixpanel.getPeople().identify( distinctId() );
	}

	@Kroll.method
	public void identify(@Kroll.argument String id) {
		mixpanel.identify(id);

		mixpanel.getPeople().identify(id);
	}

	// TODO: Upgrade MixPanel SDK to 4.1+ to support alias()
	// @Kroll.method
	// public void createAlias(@Kroll.argument String alias) {
	// 	mixpanel.alias(alias, null);
	// }
	//
	// @Kroll.method
	// public void createAliasForId(@Kroll.argument String alias, @Kroll.argument String id) {
	// 	mixpanel.alias(alias, id);
	// }

	@Kroll.method
	public void registerSuperProperties(@Kroll.argument HashMap map) {
		JSONObject props = new JSONObject(map);

		mixpanel.registerSuperPropertiesOnce(props);
	}

	@Kroll.method
	public void registerSuperPropertiesOnce(@Kroll.argument HashMap map) {
		JSONObject props = new JSONObject(map);

		mixpanel.registerSuperProperties(props);
	}

	@Kroll.method
	public void unregisterSuperProperty(@Kroll.argument String name) {
		mixpanel.unregisterSuperProperty(name);
	}

	@Kroll.method
	public void track(@Kroll.argument String name, @Kroll.argument(optional=true) HashMap map) {
		JSONObject props;
		
		if(map != null) {
			props = new JSONObject(map);
		} else {
			props = new JSONObject();
		}

		mixpanel.track(name, props);
	}

	@Kroll.method
	public void profileSet(@Kroll.argument HashMap map) {
		JSONObject props = new JSONObject(map);

		mixpanel.getPeople().set(props);
	}

	@Kroll.method
	public void profileSetOnce(@Kroll.argument HashMap map) {
		JSONObject props = new JSONObject(map);

		mixpanel.getPeople().setOnce(props);
	}

	@Kroll.method
	public void profileAppend(String name, Object value) {
		mixpanel.getPeople().append(name, value);
	}

	@Kroll.method
	public void profileIncrement(HashMap map) {
		mixpanel.getPeople().increment(map);
	}

	@Kroll.method
	public void profileTrackCharge(Object[] args) {}

	@Kroll.method
	public void profileClearCharges(Object[] args) {}

	@Kroll.method
	public void profileDeleteUser(Object[] args) {}

	@Kroll.method
	public void addPushDeviceToken(String token) {
		mixpanel.getPeople().initPushHandling(token);
	}

	// Properties
	@Kroll.getProperty
	public String distinctId()
	{
		return mixpanel.getDistinctId();
	}

	// @Kroll.getProperty
	// public int flushInterval()
	// {
	// 	return MPConfig.getInstance(iApplication.getInstance()).getFlushInterval();
	// }

}

