/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package se.hyperlab.mixpanel;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

import android.content.Context;

import com.mixpanel.android.mpmetrics.MixpanelAPI;

@Kroll.module(name="Timixpanel", id="se.hyperlab.mixpanel")
public class TimixpanelModule extends KrollModule
{

	// Standard Debugging variables
	private static final String TAG = "TimixpanelModule";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	private MixpanelAPI mixpanel;
	
	public TimixpanelModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(TAG, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	// Methods
	@Kroll.method
	public void initWithToken(@Kroll.argument String token)
	{
		Log.d(TAG, "Mixpanel initWithToken: " + token);
		mixpanel = MixpanelAPI.getInstance(TiApplication.getInstance(), token);
	}
	
	@Kroll.method
	public void identify(Object[] args) {}

	@Kroll.method
	public void createAlias(Object[] args) {}

	@Kroll.method
	public void createAliasForId(Object[] args) {}

	@Kroll.method
	public void registerSuperProperties(Object[] args) {}

	@Kroll.method
	public void registerSuperPropertiesOnce(Object[] args) {}

	@Kroll.method
	public void track(Object[] args) {}

	@Kroll.method
	public void profileSet(Object[] args) {}

	@Kroll.method
	public void profileSetOnce(Object[] args) {}

	@Kroll.method
	public void profileAppend(Object[] args) {}

	@Kroll.method
	public void profileIncrement(Object[] args) {}

	@Kroll.method
	public void profileTrackCharge(Object[] args) {}

	@Kroll.method
	public void profileClearCharges(Object[] args) {}

	@Kroll.method
	public void profileDeleteUser(Object[] args) {}

	// Properties
	@Kroll.getProperty
	public String distinctId()
	{
		return mixpanel.getDistinctId();
	}

}

